name: 'env-to-dotenv'
description: 'GitHub action that injects env variable to a dotenv file'
inputs:
  key:
    description: 'Key attribute'
    required: true
  value:
    description: 'Value attribute'
    required: true
  default:
    description: 'A default value for the key (if `value` is empty, this is used instead)'
    required: false
  nullable:
    description: 'If false, and the value resolved is empty, the variable will be omitted'
    required: false
    default: 'true'
  envPath:
    description: 'File path to write variable to'
    required: false
    default: '.env'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'gray-dark'
